// This script generates the env.js file from environment variables
// It's used during the Netlify build process

const fs = require('fs');

// Create the env.js content using environment variables
const envFileContent = `// This file is auto-generated during the build process
// DO NOT edit this file directly

window.env = {
  FIREBASE_API_KEY: "${process.env.FIREBASE_API_KEY}",
  FIREBASE_AUTH_DOMAIN: "${process.env.FIREBASE_AUTH_DOMAIN}",
  FIREBASE_DATABASE_URL: "${process.env.FIREBASE_DATABASE_URL}",
  FIREBASE_PROJECT_ID: "${process.env.FIREBASE_PROJECT_ID}",
  FIREBASE_STORAGE_BUCKET: "${process.env.FIREBASE_STORAGE_BUCKET}",
  FIREBASE_MESSAGING_SENDER_ID: "${process.env.FIREBASE_MESSAGING_SENDER_ID}",
  FIREBASE_APP_ID: "${process.env.FIREBASE_APP_ID}",
  FIREBASE_MEASUREMENT_ID: "${process.env.FIREBASE_MEASUREMENT_ID}"
};
`;

// Write the env.js file
fs.writeFileSync('js/env.js', envFileContent);

console.log('Successfully generated js/env.js from environment variables');
