[build]
  publish = "./"
  command = "node build-env.js"

[build.environment]
  # These are placeholder values. You'll set the actual values in the Netlify dashboard
  FIREBASE_API_KEY = "placeholder"
  FIREBASE_AUTH_DOMAIN = "placeholder"
  FIREBASE_DATABASE_URL = "placeholder"
  FIREBASE_PROJECT_ID = "placeholder"
  FIREBASE_STORAGE_BUCKET = "placeholder"
  FIREBASE_MESSAGING_SENDER_ID = "placeholder"
  FIREBASE_APP_ID = "placeholder"
  FIREBASE_MEASUREMENT_ID = "placeholder"
